[versions]
kotlin = "1.9.24"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization = "1.5.0"
ksp = "1.9.24-1.0.20"
autoservice-ksp = "1.0.0"
autoservice = "1.0"
tschuchortdev = "1.6.0"
kotest = "5.6.2"
mockk = "1.13.5"
kotestRunnerJunit5Jvm = "5.9.0"
openaiKotlinBom = "3.8.2"

[libraries]
kotlin-kspApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}

tschuchortdev-testing-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "tschuchortdev"}

openai-kotlin-bom = { module = "com.aallam.openai:openai-client-bom", version.ref = "openaiKotlinBom"}
openai-client = { module = "com.aallam.openai:openai-client"}
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotestRunnerJunit5Jvm" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-seialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
