
name: Run Tests on Pull Request

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew test --info
